### ISSUE TITLE
Network Information dashboard empty?

### ISSUE THREAD

**Issue by xme** [PhonePe/mantis#13]
Hi,
First of all, great project! I'm testing it and so far so good, I like it.
I'm still discovering the tools/modules implemented in Mantis but my "Network Information" dashboard remains empty. In my assets, I've TLDs, IPs and subdomains. Do you have any tips to investigate the lack of data in this dashboard? 
Tx!

**Comment by Prateek-Thakare** [comment]
Hey @xme 
Have you added IPinfo key in the IPinfo file? IPinfo is the tool which feeds network information.

**Comment by xme** [comment]
Nope, I missed this from the documentation? Let me try! Is there any other "API" that could be useful to set?

**Comment by xme** [comment]
Where did I put the token? Checked the doc briefly but... :)

**Comment by Prateek-Thakare** [comment]
In the file https://github.com/PhonePe/mantis/blob/main/mantis/modules/prerecon/IPinfo.py None `self.token = None` with your token. Obviously you will need to rebuild mantis docker with new files. Conversely, you can shell into docker and change the file via nano or vim.

**Comment by xme** [comment]
Done, tx!

**Comment by Prateek-Thakare** [comment]
Cool. Will close this issue. Please raise a new one or ping on discord if you have any doubts.
