### ISSUE TITLE
Certificates / Vulnerabilities stay empty

### ISSUE THREAD

**Issue by Emeric-hub** [PhonePe/mantis#2]
Hi,

At first, i would like to say Thanks, for this project...

It runs smoothly ... i just loos half an hour figuring out, why the smithapp always try to connect to the local MongoDb
with the account it asked to create instead of an empty authentication... (???)

I successfully scan a few assets ... IP / TLD / Subdomains ... Some with webservers ... other without...

And not certficates found ... no vulnerabilities ... 
mau be my app / infra is really secure ... but i'm not really sure ... :-)

I use default scan ...

Any idea ?

Otherwise everything work fine ...

**Comment by Ncoder2** [comment]
HI @Emeric-hub ,

Thank you ! 

mongodb is where we store our results and appsmith dashboard fetches the data from mongodb, with the docker installation we spin up all our mantis too, mongodb and appsmith together.

If your assets are on SSL (not self signed) then, it should detect. Can you confirm if you're subdomain has a ssl certificate that is not self signed ?

Note - For questions and discussion, please feel free to use our discord channel as well.

**Comment by Emeric-hub** [comment]
i tried on both TLD and subdomain (even IP) ... both of them are let's encrypt signed Certificate... (even IP provided a certificate even if not valid)

**Comment by Prateek-Thakare** [comment]
Hey @Emeric-hub 
Does this clear your doubts? Do you have any other questions? 

Also just check if there are any ports found for your assets. 

Thanks
Prateek

**Comment by Prateek-Thakare** [comment]
Hey @Emeric-hub 
Closing this issue as of now, feel free to file a new issue or reopen this if you have any further queries. 

Thanks
Prateek
