### ISSUE TITLE
Nuclei scan

### ISSUE THREAD

**Issue by Teicu** [PhonePe/mantis#20]
Hi all,  

How can we ensure Nuclei is operating optimally and utilizing all the templates at its disposal?

Could you shed some light on how Nuclei manages its template updates and its updates? Does Mantis rely on the Nuclei version installed on our systems?

I ask because my observations indicate it's only uncovering a limited number of vulnerabilities, exclusively about TLS/SSL misconfigurations. This seems rather unusual to me, especially considering I've scanned over 3,000 sites. 

Thanks

**Comment by Ncoder2** [comment]
Hi @Teicu , 
The command is present here:
https://github.com/PhonePe/mantis/blob/main/mantis/modules/scan/Nuclei.py
https://github.com/PhonePe/mantis/blob/main/mantis/modules/scan/NucleiInfo.py

If you want to run both of them, you can add this to the config (local.yml)
- moduleName: scan
        tools: [ 'DNSTwister', 'Nuclei', 'NucleiInfo', 'Corsy']
        order: 5

**Comment by Ncoder2** [comment]
This is not an issue but question.
Hi @Teicu ,hope your question is answered, if you have more questions, please post in our discord - https://discord.gg/uJV8Y3uSGu
