### ISSUE TITLE
Cutting out dependencies licensed under GPL v-3.0

### ISSUE THREAD

**Issue by Yulian83** [PhonePe/mantis#28]
Can I cut, remove, or replace dependencies licensed under GPL v-3.0 or CC0-1.0?

### Affected Packages
- [puredns](https://github.com/d3mondev/puredns)
- [Findcdn](https://github.com/cisagov/findcdn.git)
- [Corsy](https://github.com/s0md3v/Corsy)

**Comment by Prateek-Thakare** [comment]
Hi @Yulian83 
If you desire to remove these packages and binaries from the Mantis, please follow the following steps:
- Remove the installation commands from the Dockerfile, you can easily search using the package name. 
- Remove the tool names from the config. 
- [Optional] Remove the python files for respective packages in the modules folder. Note that this is optional and Mantis will work even if you don't remove these files. 
- Rebuild the docker by running the setup script again. 

Please note that removing these packages will affect the workflows as some tools expect input derived which is the output of these tools. 

Do let me know if you have any doubts.
