### ISSUE TITLE
New Version Pop-Up

### ISSUE THREAD

**Issue by maajix** [PhonePe/mantis#3]
Hey there is a pop up saying: _Hey! There is a new version of Appsmith available. Please consider refreshing your window._ 
When clicking refresh it is not going away and re-appears.

![image](https://github.com/PhonePe/mantis/assets/49589091/28d03253-9cfd-439c-997d-cf04db7323d3)

**Comment by maajix** [comment]
updating appsmith seems to fix the issue

**Comment by Prateek-Thakare** [comment]
Hey @maajix 
Thanks for the issue and solution to it.
