### ISSUE TITLE
List existing organisations?

### ISSUE THREAD

**Issue by xme** [PhonePe/mantis#34]
Hi,
I've a bunch of organizations onboarded in Mantis. I would like to re-scan them at regular interval through a cron job.
Is there an easy way to get the list of organizations? (to fetch the list and loop over all orgs)
Tx!

**Comment by Prateek-Thakare** [comment]
Hi @xme 
Unfortunately, as of now, this can only be viewed via the dashboard. I will push a change in a day or two with a mantis subcommand which would ease this and list all the orgs on the cmd too.

**Comment by Prateek-Thakare** [comment]
Hi @xme 
The feature was added. With the latest release, you can use following command on cli to get the orgs:
`mantis list orgs`

**Comment by xme** [comment]
Great! Time to upgrade now! :-)
