### ISSUE TITLE
Enhance Mantis "list" command

### ISSUE THREAD

**Issue by 0xbharath** [PhonePe/mantis#37]
### Discussed in https://github.com/PhonePe/mantis/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **0xbharath** June 19, 2024</sup>
@Prateek-Thakare @Ncoder2  Can we have a "list" as a top level command for mantis along with onboard and scan? I feel that this can come in handy when one wants to list orgs that are onboarded to the Mantis and other details. I have onboarded 20+ orgs on Mantis and it is not comfortable to do a DB query or go to dashboard everytime to get this list.

Example:

```
$ mantis list orgs
org1 
org2
org2
```

</div>

This is a good issue to pick up for new contributors. `mantis list` is already implemented. We need to enhance the `mantis list` command with more features

1. To list the TLDs under an org. something like

```
mantis list -o org tlds
mantis list -o navigalactic tlds
navigalactic.com
navigalactic.in
navigalatic.org
```

**Comment by Prateek-Thakare** [comment]
This command can be enhanced to list the subdomains found after a certain date based on timestamps. 
`mantis list -o navigalactic --subs --after 2024-25-07`
This should list the subdomains found after 2024-25-07. Similarly before and between constructs can be added to list subdomains.

**Comment by dmdhrumilmistry** [comment]
Can you assign this to me? I've raised for it

**Comment by dmdhrumilmistry** [comment]
this issue can be closed since PR is merged

**Comment by 0xbharath** [comment]
Thanks for your contribution @dmdhrumilmistry !
