### ISSUE TITLE
typo in ApiScanner

### ISSUE THREAD

**Issue by lutilm** [PhonePe/mantis#5]
Typo in "response".

https://github.com/PhonePe/mantis/blob/0bda292e815bcfc093a74f81a810303072e0b9b9/mantis/tool_base_classes/apiScanner.py#L53C1-L54C1

**Comment by Prateek-Thakare** [comment]
Hey @lutilm 
Thanks for pointing the typo. Fixed this in latest commit.

**Comment by lutilm** [comment]
thanks to you for this great project!
