### ISSUE TITLE
mantis/modules/alerter.py For error

### ISSUE THREAD

**Issue by jsdysq** [PhonePe/mantis#66]
if channel_type == 'mattermost':
                        if isinstance(team.channel[channel_type], list):
                            for webhook in team.channel[channel_type];
                                if team.scanEfficiency == True:
                                    Notifications.send_mattermost_notifications(scan_efficiency_blocks, webhook)
                                Notifications.send_mattermost_notifications(slack_blocks, webhook)
                        else:
                            logging.error("Mattermost must provide a list of webhooks, check local.yml")

for webhook in team.channel[channel_type]; Should write: This makes my program report an error.

**Comment by Prateek-Thakare** [comment]
Hey 
Can you post the error here?

**Comment by Prateek-Thakare** [comment]
This is fixed in https://github.com/PhonePe/mantis/pull/67. Thanks for raising the issue.
