### ISSUE TITLE
can not get over registration page

### ISSUE THREAD

**Issue by zinwelzl** [PhonePe/mantis#73]
New clean installation, register and select "What is your general development proficiency?",  "What would you like to use Appsmith for?"
and after "Get started", registration page show again.
I try few times, and can not get over registration page.

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

**Comment by 0xbharath** [comment]
Sorry. Missed this issue.

Were you able to resolve this? Can you open DevTools Console and see if there are any errors?

**Comment by zinwelzl** [comment]
fresh ubuntu install works, my docker was problem
